### ISSUE TITLE
wavefrontsize64 not supported on GFX10 while it is on GFX11. Intended or not?

### ISSUE THREAD

**Issue by Epliz** [ROCm-Developer-Tools/hipamd#59] opened 2023-01-29 15:31 UTC
Hi,

I would like to compile my kernels for GFX10 with wavefront64 enabled, but I get the following compilation error:
```
/opt/rocm-5.4.1/include/hip/hip_runtime.h:41:2: error: HIP is not supported on GFX10 with wavefront size 64
```
But it happily compiles for GFX11. I don't have GFX11 to test, so I can't say if it actually works correctly or not on that target.
Is it what you wanted to have wavefront64 enabled for GFX11 but not GFX10? The architectures seem similar enough that it seems to me that it should either be working on both or none.

I would really appreciate to have the wavefront64 mode working on gfx10 to see if I get better performance with it.

Best regards,
Epliz

**Comment by Epliz** [comment] 2023-02-15 07:50
Hi @satyanveshd (just asking as you seem to contribute to hipRTC), 
Any idea on that issue?

**Comment by satyanveshd** [comment] 2023-02-15 10:17
As far as I remember, Compiler defines the wavefront size and it is 32 both for gfx10 and gfx11.  I don't think wavefrontsize64 is supported on these.  We might need to change it to not allow it for gfx11 as well. But I would like @yxsamliu and @mangupta to comment on the right behavior.

**Comment by yxsamliu** [comment] 2023-02-15 14:41
gfx11 does not support wave64.

we need to update https://github.com/ROCm-Developer-Tools/HIP/blob/586165ebc281eb9461898a5b2abbc74595f5d97d/include/hip/hip_runtime.h#L40

we could use the macro `__GFX8__` and `__GFX9__` instead

**Comment by Epliz** [comment] 2023-02-16 06:58
Hi @yxsamliu ,
The rdna3 ISA document section 2.1 indicates that both wave32 and wave64 are supported in hardware. I guess you meant that in hip only wave32 will be supported?

**Comment by yxsamliu** [comment] 2023-02-16 14:01
In wave64 mode, some cross-lane instructions only support 32 lanes, which makes hardware support of some cross-lane HIP functions impossible. Mainly due to that reason, HIP does not support wave64 for gfx10 and gfx11.

**Comment by Epliz** [comment] 2023-02-25 12:53
Hi @yxsamliu , @yxsamliu ,
Thanks for the answer.
I just saw that the issue was addressed in the HIP repo (not this one)?

**Comment by satyanveshd** [comment] 2023-02-27 14:50
Hi @Epliz,  Yes. The issue is addressed with https://github.com/ROCm-Developer-Tools/HIP/pull/3170/commits/83f163154f4421283978636db71bb23bfff7be6b.  Please verify and close the issue. Thanks.

**Closed as completed** 2023-02-27 18:06 UTC
